---
title: "K means"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Which chemical properties influence the quality of red wines

```{r,include=FALSE}
# Load libraries
library(tidyverse)
library(corrplot)
library(gridExtra)
library(GGally)
library(knitr)
```

Data
```{r}
# Read the stats
wines <- read.csv("wineQualityReds.csv")
wines <- wines[,2:13]
kable(head(wines))
```

```{r}
# Histogram for each Attribute
wines %>%
  gather(Attributes, value) %>%
  ggplot(aes(x=value, fill=Attributes)) +
  geom_histogram(colour="black", show.legend=FALSE) +
  facet_wrap(~Attributes, scales="free_x") +
  labs(x="Values", y="Frequency",
       title="Red Wine Attributes - Histograms") +
  theme_bw()
```


```{r}
# Density plot for each Attribute
wines %>%
  gather(Attributes, value) %>%
  ggplot(aes(x=value, fill=Attributes)) +
  geom_density(colour="black", alpha=0.5, show.legend=FALSE) +
  facet_wrap(~Attributes, scales="free_x") +
  labs(x="Values", y="Density",
       title="Red Wine Attributes - Density plots") +
  theme_bw()
```


```{r}
# Boxplot for each Attribute  
wines %>%
  gather(Attributes, values, c(1:4, 6:12)) %>%
  ggplot(aes(x=reorder(Attributes, values, FUN=median), y=values, fill=Attributes)) +
  geom_boxplot(show.legend=FALSE) +
  labs(title="Wines Attributes - Boxplots") +
  theme_bw() +
  theme(axis.title.y=element_blank(),
        axis.title.x=element_blank()) +
  ylim(0, 35) +
  coord_flip()
```


```{r}
# Correlation matrix 
corrplot(cor(wines), type="upper", method="ellipse", tl.cex=0.9)
```



```{r}
# Relationship between fixed.acidity and citric.acid
ggplot(wines, aes(x=fixed.acidity, y=citric.acid)) +
  geom_point() +
  geom_smooth(method="lm", se=FALSE) +
  labs(title="Wines Attributes",
       subtitle="Relationship between fixed acidity and citric acid") +
  theme_bw()
```



```{r}
# Normalization
winesNorm <- as.data.frame(scale(wines))

# Original data
p1 <- ggplot(wines, aes(x=alcohol, y=citric.acid)) +
  geom_point() +
  labs(title="Original data") +
  theme_bw()

# Normalized data 
p2 <- ggplot(winesNorm, aes(x=alcohol, y=citric.acid)) +
  geom_point() +
  labs(title="Normalized data") +
  theme_bw()

# Subplot
grid.arrange(p1, p2, ncol=2)

```


```{r}
# Execution of k-means with k=2
set.seed(1234)
wines_k2 <- kmeans(winesNorm, centers=2)
wines_k2$cluster
```


```{r}
# Cluster centers
wines_k2$centers
```

```{r}
# Between-cluster sum of squares
wines_k2$betweenss
```

```{r}
# Within-cluster sum of squares
wines_k2$withinss
```

```{r}
# Total within-cluster sum of squares 
wines_k2$tot.withinss
```

```{r}
# Total sum of squares
wines_k2$totss
```


```{r}
bss <- numeric()
wss <- numeric()

# Run the algorithm for different values of k 
set.seed(1234)

for(i in 1:10){
  
  # For each k, calculate betweenss and tot.withinss
  bss[i] <- kmeans(winesNorm, centers=i)$betweenss
  wss[i] <- kmeans(winesNorm, centers=i)$tot.withinss
  
}

# Between-cluster sum of squares vs Choice of k
p3 <- qplot(1:10, bss, geom=c("point", "line"), 
            xlab="Number of clusters", ylab="Between-cluster sum of squares") +
  scale_x_continuous(breaks=seq(0, 10, 1)) +
  theme_bw()

# Total within-cluster sum of squares vs Choice of k
p4 <- qplot(1:10, wss, geom=c("point", "line"),
            xlab="Number of clusters", ylab="Total within-cluster sum of squares") +
  scale_x_continuous(breaks=seq(0, 10, 1)) +
  theme_bw()
```


```{r}
# Subplot
grid.arrange(p3, p4, ncol=2)
```

We choose k=3


```{r}
# Execution of k-means with k=3
set.seed(1234)

wines_k3 <- kmeans(winesNorm, centers=3)

# Mean values of each cluster
aggregate(wines, by=list(wines_k3$cluster), mean)
```


```{r}
ggpairs(cbind(wines, Cluster=as.factor(wines_k3$cluster)),
        columns=6:12, aes(colour=Cluster, alpha=0.5),
        lower=list(continuous="points"),
        upper=list(continuous="blank"),
        axisLabels="none", switch="both") +
  theme_bw()
```







